# Generated by Django 5.2.14 on 2026-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("interval", models.CharField(max_length=5)),
                ("open_time", models.DateTimeField()),
                ("close_time", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=30)),
                ("quote_volume", models.DecimalField(decimal_places=8, max_digits=30)),
                ("trades", models.PositiveIntegerField()),
                (
                    "taker_buy_base_volume",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                (
                    "taker_buy_quote_volume",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-open_time"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "interval", "-open_time"],
                        name="candle_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "interval", "open_time"), name="uniq_candle"
                    )
                ],
            },
        ),
    ]
