# Generated by Django 5.2.14 on 2026-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candle",
            name="interval",
            field=models.CharField(
                choices=[
                    ("1m", "1 minute"),
                    ("3m", "3 minutes"),
                    ("5m", "5 minutes"),
                    ("15m", "15 minutes"),
                    ("30m", "30 minutes"),
                    ("1h", "1 hour"),
                    ("2h", "2 hours"),
                    ("4h", "4 hours"),
                    ("6h", "6 hours"),
                    ("8h", "8 hours"),
                    ("12h", "12 hours"),
                    ("1d", "1 day"),
                    ("3d", "3 days"),
                    ("1w", "1 week"),
                    ("1M", "1 month"),
                ],
                default="15m",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="symbol",
            field=models.CharField(
                choices=[
                    ("BTCUSDT", "BTC / USDT"),
                    ("ETHUSDT", "ETH / USDT"),
                    ("BNBUSDT", "BNB / USDT"),
                    ("SOLUSDT", "SOL / USDT"),
                    ("XRPUSDT", "XRP / USDT"),
                    ("DOGEUSDT", "DOGE / USDT"),
                    ("ADAUSDT", "ADA / USDT"),
                    ("AVAXUSDT", "AVAX / USDT"),
                    ("LINKUSDT", "LINK / USDT"),
                    ("TRXUSDT", "TRX / USDT"),
                ],
                default="BTCUSDT",
                max_length=20,
            ),
        ),
    ]
