# Generated by Django 5.2.14 on 2026-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_candle_interval_alter_candle_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        choices=[
                            ("BTCUSDT", "BTC / USDT"),
                            ("ETHUSDT", "ETH / USDT"),
                            ("BNBUSDT", "BNB / USDT"),
                            ("SOLUSDT", "SOL / USDT"),
                            ("XRPUSDT", "XRP / USDT"),
                            ("DOGEUSDT", "DOGE / USDT"),
                            ("ADAUSDT", "ADA / USDT"),
                            ("AVAXUSDT", "AVAX / USDT"),
                            ("LINKUSDT", "LINK / USDT"),
                            ("TRXUSDT", "TRX / USDT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("3m", "3 minutes"),
                            ("5m", "5 minutes"),
                            ("15m", "15 minutes"),
                            ("30m", "30 minutes"),
                            ("1h", "1 hour"),
                            ("2h", "2 hours"),
                            ("4h", "4 hours"),
                            ("6h", "6 hours"),
                            ("8h", "8 hours"),
                            ("12h", "12 hours"),
                            ("1d", "1 day"),
                            ("3d", "3 days"),
                            ("1w", "1 week"),
                            ("1M", "1 month"),
                        ],
                        max_length=5,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "sum_open_interest",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                (
                    "sum_open_interest_value",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "period", "-timestamp"], name="oi_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "period", "timestamp"),
                        name="uniq_open_interest",
                    )
                ],
            },
        ),
    ]
