# Generated by Django 5.2.14 on 2026-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_openinterest"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        choices=[
                            ("BTCUSDT", "BTC / USDT"),
                            ("ETHUSDT", "ETH / USDT"),
                            ("BNBUSDT", "BNB / USDT"),
                            ("SOLUSDT", "SOL / USDT"),
                            ("XRPUSDT", "XRP / USDT"),
                            ("DOGEUSDT", "DOGE / USDT"),
                            ("ADAUSDT", "ADA / USDT"),
                            ("AVAXUSDT", "AVAX / USDT"),
                            ("LINKUSDT", "LINK / USDT"),
                            ("TRXUSDT", "TRX / USDT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("funding_time", models.DateTimeField()),
                ("funding_rate", models.DecimalField(decimal_places=10, max_digits=12)),
                (
                    "mark_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-funding_time"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-funding_time"], name="fr_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "funding_time"), name="uniq_funding_rate"
                    )
                ],
            },
        ),
    ]
