# Generated by Django 5.2.14 on 2026-05-10 23:32, then hand-edited to add
# the RunPython backfill step.

from django.db import migrations, models
from django.db.models import F


def populate_delta(apps, schema_editor):
    """Backfill `Candle.delta` for every existing row.

    Δ = 2 × taker_buy_base_volume − volume. The formula is duplicated
    inline (rather than imported from `feature.services.delta`) on
    purpose: Django migrations are expected to be self-contained — if
    `feature` is renamed or its service module restructured, this
    migration must still apply cleanly years from now against any
    point-in-time checkout. The same formula is also the canonical one
    in `feature.services.delta.compute_delta`.

    Using F-expressions makes this a single SQL UPDATE — orders of
    magnitude faster than iterating rows in Python, which matters once
    the candle table has many tens of thousands of rows per pair.
    """
    Candle = apps.get_model("data", "Candle")
    Candle.objects.update(delta=2 * F("taker_buy_base_volume") - F("volume"))


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_fundingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="candle",
            name="delta",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.RunPython(populate_delta, reverse_code=migrations.RunPython.noop),
    ]
