# Generated by Django 5.2.14 on 2026-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_candle_delta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        choices=[
                            ("BTCUSDT", "BTC / USDT"),
                            ("ETHUSDT", "ETH / USDT"),
                            ("BNBUSDT", "BNB / USDT"),
                            ("SOLUSDT", "SOL / USDT"),
                            ("XRPUSDT", "XRP / USDT"),
                            ("DOGEUSDT", "DOGE / USDT"),
                            ("ADAUSDT", "ADA / USDT"),
                            ("AVAXUSDT", "AVAX / USDT"),
                            ("LINKUSDT", "LINK / USDT"),
                            ("TRXUSDT", "TRX / USDT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("side", models.CharField(max_length=10)),
                ("price_low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price_high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("source_open_time", models.DateTimeField()),
                ("strength", models.FloatField()),
                ("notional", models.DecimalField(decimal_places=8, max_digits=30)),
                ("long_bias", models.FloatField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-start_time"], name="cluster_segment_lookup_idx"
                    )
                ],
            },
        ),
    ]
