# Generated by Django 5.2.14 on 2026-05-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feature", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CumulativeVolumeDelta",
        ),
    ]
